#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

APP_DIR="$( dirname "${BASH_SOURCE[0]}" )"

available_generators=$(ls ${APP_DIR}/generators)

echo "Select generator: "
PS3="Choose generator number: "
select select_generator in ${available_generators[@]} quit
do
  case ${select_generator} in
    quit ) echo "Bye."; exit;;
    * ) if [[ ! -z ${select_generator} ]] && [[ ${available_generators[@]} =~ ${select_generator} ]]; then
          source ${APP_DIR}/generators/${select_generator}
        else
          echo "Invalid option. Try again or choose quit."
        fi
  esac
done

exit
