#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

APP_DIR="$( dirname "${BASH_SOURCE[0]}" )"

available_generators=$(ls ${APP_DIR}/generators)

if [[ $# -eq 0 ]] || [[ ! ${available_generators[@]} =~ $1 ]]; then
  echo "Wrong input."
  echo "Usage: ./m2-generate [ "${available_generators[@]}" ]"

  exit
fi

for generator in ${available_generators[@]}; do
  if [[ $1 == ${generator} ]]; then
    GENERATOR_KEYWORD=$1
    source ${APP_DIR}/generators/${generator}
  else
    continue
  fi
done

exit
