#!/usr/bin/env bash

echo "Vendor name: "
read vendor_name
echo "Module name: "
read module_name

if [[ ! -d app/code/${vendor_name}/${module_name} ]]; then
  echo "Module ${vendor_name}_${module_name} does not exist!"
  echo "Generate a module first."

  exit
fi
