#!/usr/bin/env bash

echo "Vendor name: "
read VENDOR_NAME
echo "Module name: "
read MODULE_NAME

MODULE_PATH=app/code/${VENDOR_NAME}/${MODULE_NAME}

if [[ ! -d ${MODULE_PATH} ]]; then
  echo "Module ${VENDOR_NAME}_${MODULE_NAME} does not exist!"
  echo "Generate a module first."

  exit
fi
