#!/bin/bash

source ${APP_DIR}/core/check_module

  echo "Controller name: "
  read -r controller_name

if [[ ! -d ${MODULE_PATH}/Controller ]]; then
  mkdir ${MODULE_PATH}/Controller
fi

if [[ ! -d ${MODULE_PATH}/Controller/${controller_name} ]]; then
  mkdir ${MODULE_PATH}/Controller/${controller_name}
fi

echo "Controller action: "
read -r controller_action

if [[ -f ${MODULE_PATH}/Controller/${controller_name}/${controller_action}.php ]]; then
  echo "Controller action ${controller_action} already exists!"

  exit
else
  cat ${APP_DIR}/templates/Controller/controller-action_php \
  | sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g" \
  | sed "s/{MODULE_NAME}/${MODULE_NAME}/g" \
  | sed "s/{CONTROLLER_NAME}/${controller_name}/g" \
  | sed "s/{ACTION_NAME}/${controller_action}/g" \
  > ${MODULE_PATH}/Controller/${controller_name}/${controller_action}.php

  echo "File ${controller_action}.php generated successfully."
fi

exit
