#!/usr/bin/env bash

source ${APP_DIR}/core/check_module

module_path=app/code/${vendor_name}/${module_name}

  echo "Controller name: "
  read controller_name

if [[ ! -d ${module_path}/${controller_name} ]]; then
  mkdir ${module_path}/${controller_name}
fi

echo "Controller action: "
read controller_action

if [[ -f ${module_path}/${controller_name}/${controller_action}.php ]]; then
  echo "Controller action ${controller_action} already exists!"

  exit
else
  cat ${APP_DIR}/templates/Controller/ControllerAction.php \
  | sed "s/{VENDOR_NAME}/${vendor_name}/g" \
  | sed "s/{MODULE_NAME}/${module_name}/g" \
  | sed "s/{CONTROLLER_NAME}/${controller_name}/g" \
  | sed "s/{ACTION_NAME}/${controller_action}/g" \
  > ${module_path}/${controller_name}/${controller_action}.php

  echo "File ${controller_action}.php generated successfully."
fi

exit
