#!/bin/bash

source ${APP_DIR}/core/check_module

echo "Model name: "
read -r model_name

if [[ -f ${MODULE_PATH}/Model/${model_name}.php ]]; then
  echo "Model ${model_name} already exists!"

  exit
fi


if [[ -f ${MODULE_PATH}/Model/ResourceModel/${model_name}.php ]]; then
  echo "Resource model ${model_name} already exists!"

  exit
fi


if [[ -f ${MODULE_PATH}/Model/ResourceModel/${model_name}/Collection.php ]]; then
  echo "${model_name} collection already exists!"

  exit
fi

echo "Table name: "
read -r table_name

echo "ID column value: "
read -r id_value

if [[ ! -d ${MODULE_PATH}/Model ]]; then
  mkdir ${MODULE_PATH}/Model
fi

if [[ ! -d ${MODULE_PATH}/Model/ResourceModel ]]; then
  mkdir ${MODULE_PATH}/Model/ResourceModel
fi

if [[ ! -d ${MODULE_PATH}/Model/ResourceModel/${model_name} ]]; then
  mkdir ${MODULE_PATH}/Model/ResourceModel/${model_name}
fi

sed -e "s/{VENDOR_NAME}/${VENDOR_NAME}/g" -e "s/{MODULE_NAME}/${MODULE_NAME}/g" -e "s/{MODEL_NAME}/${model_name}/g" ${APP_DIR}/templates/model/model-name_php > ${MODULE_PATH}/Model/${model_name}.php

echo "File Model/${model_name}.php generated successfully."

sed -e "s/{VENDOR_NAME}/${VENDOR_NAME}/g" -e "s/{MODULE_NAME}/${MODULE_NAME}/g" -e "s/{MODEL_NAME}/${model_name}/g" -e "s/{TABLE_NAME}/${table_name}/g" -e "s/{ID_VALUE}/${id_value}/g" ${APP_DIR}/templates/model/resourcemodel/model-name_php > ${MODULE_PATH}/Model/ResourceModel/${model_name}.php

echo "File Model/ResourceModel/${model_name}.php generated successfully."

sed -e "s/{VENDOR_NAME}/${VENDOR_NAME}/g" -e "s/{MODULE_NAME}/${MODULE_NAME}/g" -e "s/{MODEL_NAME}/${model_name}/g" ${APP_DIR}/templates/model/resourcemodel/modelname/collection_php > ${MODULE_PATH}/Model/ResourceModel/${model_name}/Collection.php

echo "File Model/ResourceModel/${model_name}/Collection.php generated successfully."

exit
