#!/usr/bin/env bash

source ${APP_DIR}/core/*

echo "Model name: "
read model_name

if [[ -f ${MODULE_PATH}/Model/${model_name}.php ]]; then
  echo "Model ${model_name} already exists!"

  exit
fi


if [[ -f ${MODULE_PATH}/Model/ResourceModel/${model_name}.php ]]; then
  echo "Resource model ${model_name} already exists!"

  exit
fi


if [[ -f ${MODULE_PATH}/Model/ResourceModel/${model_name}/Collection.php ]]; then
  echo "${model_name} collection already exists!"

  exit
fi

echo "Table name: "
read table_name

echo "ID column value: "
read id_value

if [[ ! -d ${MODULE_PATH}/Model ]]; then
  mkdir ${MODULE_PATH}/Model
fi

if [[ ! -d ${MODULE_PATH}/Model/ResourceModel ]]; then
  mkdir ${MODULE_PATH}/Model/ResourceModel
fi

if [[ ! -d ${MODULE_PATH}/Model/ResourceModel/${model_name} ]]; then
  mkdir ${MODULE_PATH}/Model/ResourceModel/${model_name}
fi

cat ${APP_DIR}/templates/Model/ModelName.php \
| sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g" \
| sed "s/{MODULE_NAME}/${MODULE_NAME}/g" \
| sed "s/{MODEL_NAME}/${model_name}/g" \
> ${MODULE_PATH}/Model/${model_name}.php

echo "File Model/${model_name}.php generated successfully."

cat ${APP_DIR}/templates/Model/ResourceModel/ModelName.php \
| sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g" \
| sed "s/{MODULE_NAME}/${MODULE_NAME}/g" \
| sed "s/{MODEL_NAME}/${model_name}/g" \
| sed "s/{TABLE_NAME}/${table_name}/g" \
| sed "s/{ID_VALUE}/${id_value}/g" \
> ${MODULE_PATH}/Model/ResourceModel/${model_name}.php

echo "File Model/ResourceModel/${model_name}.php generated successfully."

cat ${APP_DIR}/templates/Model/ResourceModel/ModelName/Collection.php \
| sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g" \
| sed "s/{MODULE_NAME}/${MODULE_NAME}/g" \
| sed "s/{MODEL_NAME}/${model_name}/g" \
> ${MODULE_PATH}/Model/ResourceModel/${model_name}/Collection.php

echo "File Model/ResourceModel/${model_name}/Collection.php generated successfully."

exit
