#!/usr/bin/env bash

echo "Vendor name: "
read vendor_name
echo "Module name: "
read module_name


MODULE_PATH=app/code/${vendor_name}/${module_name}

if [[ ! -d app ]]; then
  mkdir app
fi

if [[ ! -d app/code ]]; then
  mkdir app/code
fi

if [[ ! -d app/code/${vendor_name} ]]; then
  mkdir app/code/${vendor_name}
fi

if [[ -d app/code/${vendor_name}/${module_name} ]]; then
  echo "Module ${vendor_name}_${module_name} already exists!"
  echo "Use another module name."
else
  mkdir ${MODULE_PATH}

  if [[ ! -d ${MODULE_PATH}/etc ]]; then
    mkdir ${MODULE_PATH}/etc
  fi

  if [[ -f ${MODULE_PATH}/etc/module.xml ]]; then
    echo "File module.xml already exists!"
  else
    cat ${APP_DIR}/templates/etc/module.xml \
    | sed "s/{VENDOR_NAME}/${vendor_name}/g" \
    | sed "s/{MODULE_NAME}/${module_name}/g" \
    > ${MODULE_PATH}/etc/module.xml

    echo "File module.xml generated successfully."
  fi

  if [[ -f ${MODULE_PATH}/registration.php ]]; then
    echo "File registration.php already exists!"
  else
    cat ${APP_DIR}/templates/registration.php \
    | sed "s/{VENDOR_NAME}/${vendor_name}/g" \
    | sed "s/{MODULE_NAME}/${module_name}/g" \
    > ${MODULE_PATH}/registration.php

    echo "File registration.php generated successfully."
  fi

  if [[ -f ${MODULE_PATH}/composer.json ]]; then
    echo "File composer.json already exists!"
  else
    cat ${APP_DIR}/templates/composer.json \
    | sed "s/{VENDOR_NAME}/${vendor_name}/g" \
    | sed "s/{MODULE_NAME}/${module_name}/g" \
    > ${MODULE_PATH}/composer.json

    echo "File composer.json generated successfully."
  fi

  echo "Module ${vendor_name}_${module_name} generation finished successfully."
fi

exit
