#!/bin/bash

echo "Vendor name: "
read -r VENDOR_NAME
echo "Module name: "
read -r MODULE_NAME


MODULE_PATH=app/code/${VENDOR_NAME}/${MODULE_NAME}

if [[ ! -d app ]]; then
  mkdir app
fi

if [[ ! -d app/code ]]; then
  mkdir app/code
fi

if [[ ! -d app/code/${VENDOR_NAME} ]]; then
  mkdir app/code/${VENDOR_NAME}
fi

if [[ -d app/code/${VENDOR_NAME}/${MODULE_NAME} ]]; then
  echo "Module ${VENDOR_NAME}_${MODULE_NAME} already exists!"
  echo "Use another module name."
else
  mkdir ${MODULE_PATH}

  if [[ ! -d ${MODULE_PATH}/etc ]]; then
    mkdir ${MODULE_PATH}/etc
  fi

  if [[ -f ${MODULE_PATH}/etc/module.xml ]]; then
    echo "File module.xml already exists!"
  else
    cat ${APP_DIR}/templates/etc/module_xml | sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g"; "s/{MODULE_NAME}/${MODULE_NAME}/g" > ${MODULE_PATH}/etc/module.xml

    echo "File module.xml generated successfully."
  fi

  if [[ -f ${MODULE_PATH}/registration.php ]]; then
    echo "File registration.php already exists!"
  else
    cat ${APP_DIR}/templates/registration.php | sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g"; "s/{MODULE_NAME}/${MODULE_NAME}/g" > ${MODULE_PATH}/registration.php

    echo "File registration.php generated successfully."
  fi

  if [[ -f ${MODULE_PATH}/composer.json ]]; then
    echo "File composer.json already exists!"
  else
    cat ${APP_DIR}/templates/composer_json | sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g"; "s/{MODULE_NAME}/${MODULE_NAME}/g" > ${MODULE_PATH}/composer.json

    echo "File composer.json generated successfully."
  fi

  echo "Module ${VENDOR_NAME}_${MODULE_NAME} generation finished successfully."
fi

exit
