#!/usr/bin/env bash

source ${APP_DIR}/core/check_module
source ${APP_DIR}/core/select_area


echo "Router name: "
read -r router_name

if [[ ! -d ${MODULE_PATH}/etc ]]; then
  mkdir ${MODULE_PATH}/etc
fi

if [[ ! -d ${MODULE_PATH}/etc/${AREA} ]]; then
  mkdir ${MODULE_PATH}/etc/${AREA}
fi

if [[ ! -f ${MODULE_PATH}/etc/${AREA}/di.xml ]]; then
  di_xml=$(cat ${APP_DIR}/templates/etc/di.xml)
  echo "\
${di_xml}\
" > ${MODULE_PATH}/etc/${AREA}/di.xml

  echo "File ${AREA}/di.xml generated successfully."
fi

if [[ -z $(cat app/code/Test/Module/etc/${AREA}/di.xml| grep "${router_name}") ]]; then
di_xml_temp=$(cat ${MODULE_PATH}/etc/${AREA}/di.xml | sed 's#</config>##g')
echo "\
${di_xml_temp}\
" > ${MODULE_PATH}/etc/${AREA}/di.xml
di_router=$(cat ${APP_DIR}/templates/etc/di-templates/di-router \
| sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g" \
| sed "s/{MODULE_NAME}/${MODULE_NAME}/g" \
| sed "s/{ROUTER_NAME}/${router_name}/g")
echo "\
${di_router}
" >> ${MODULE_PATH}/etc/${AREA}/di.xml
echo "\
</config>
" >> ${MODULE_PATH}/etc/${AREA}/di.xml
echo "File ${AREA}/di.xml updated successfully."
else
echo "Router settings already exist in di.xml, no changes made!"
fi


if [[ ! -d ${MODULE_PATH}/Controller ]]; then
  mkdir ${MODULE_PATH}/Controller
fi

if [[ -f ${MODULE_PATH}/Controller/Router.php ]]; then
  echo "File Router.php already exists!"

  exit
else
  cat ${APP_DIR}/templates/Controller/Router.php \
  | sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g" \
  | sed "s/{MODULE_NAME}/${MODULE_NAME}/g" \
  > ${MODULE_PATH}/Controller/Router.php

  echo "File Router.php generated successfully."
fi

exit
