#!/usr/bin/env bash

source ${APP_DIR}/inc/check_module

echo "Route id: "
read route_id
echo "Route frontname: "
read route_frontname

module_path=app/code/${vendor_name}/${module_name}

if [[ ! -d ${module_path}/etc ]]; then
  mkdir ${module_path}/etc
fi

if [[ ! -d ${module_path}/etc/frontend ]]; then
  mkdir ${module_path}/etc/frontend
fi

if [[ -f ${module_path}/etc/frontend/routes.xml ]]; then
  echo "File routes.xml already exists!"
  exit
else
  cat ${APP_DIR}/templates/etc/frontend/routes.xml \
  | sed "s/{VENDOR_NAME}/${vendor_name}/g" \
  | sed "s/{MODULE_NAME}/${module_name}/g" \
  | sed "s/{ROUTE_ID}/${route_id}/g" \
  | sed "s/{ROUTE_FRONTNAME}/${route_frontname}/g" \
  > ${module_path}/etc/frontend/routes.xml

  echo "File routes.xml generated successfully."
fi

exit
