#!/usr/bin/env bash

source ${APP_DIR}/core/check_module
source ${APP_DIR}/core/select_area

echo "Route id: "
read route_id
echo "Route frontname: "
read route_frontname

if [[ ! -d ${MODULE_PATH}/etc ]]; then
  mkdir ${MODULE_PATH}/etc
fi

if [[ ! -d ${MODULE_PATH}/etc/${AREA} ]]; then
  mkdir ${MODULE_PATH}/etc/${AREA}
fi

if [[ -f ${MODULE_PATH}/etc/${AREA}/routes.xml ]]; then
  echo "File routes.xml already exists!"
  exit
else
  cat ${APP_DIR}/templates/etc/routes.xml \
  | sed "s/{VENDOR_NAME}/${VENDOR_NAME}/g" \
  | sed "s/{MODULE_NAME}/${MODULE_NAME}/g" \
  | sed "s/{ROUTE_ID}/${route_id}/g" \
  | sed "s/{ROUTE_FRONTNAME}/${route_frontname}/g" \
  > ${MODULE_PATH}/etc/${AREA}/routes.xml

  echo "File ${AREA}/routes.xml generated successfully."
fi

exit
